#!/bin/bash
BINDIR=/usr/bin
SBINDIR=/usr/sbin
LIBDIR=/usr/lib/bumblebee
INITDIR=/etc/init.d
XORG_MODULEPATH=/usr/lib/nvidia-optimus,/usr/lib/xorg/modules
CMD_SVC_STOP='rc-service bumblebee stop'
if [ "$(uname -m)" == "x86_64" ]; then
	LIBDIR=/usr/lib64/bumblebee
	XORG_MODULEPATH=/usr/lib64/nvidia-optimus,/usr/lib64/xorg/modules
fi
