#!/bin/bash
OVERRIDEAUTODETECT=false
while [ $# -gt 0 ]; do
    case "$1" in
      --force)
        OVERRIDEAUTODETECT=true
        ;;
      --)
        shift
        break
        ;;
      *)
        echo "Unknown option: $1"
        exit 255
        ;;
    esac
    shift
done
if ! $OVERRIDEAUTODETECT; then
    if [ ! -f "/etc/bumblebee" ]; then
        echo "There is no ancient version to cleanup, to override this, run"
        echo "this program with the --force option. Note: this cleaner can"
        echo "only cleanup versions after 1.4.13 (released March 17th, 2011)."
        exit 1
    fi
fi

# ok, the old uninstaller is horrible, do not even use it
[ -x /etc/init.d/bumblebee ] && /etc/init.d/bumblebee disable
[ -x /usr/local/bin/bumblebee-enablecard ] && /usr/local/bin/bumblebee-enablecard

# Distro-specific cleanups
if grep -iq ubuntu /etc/issue; then
    if [[ $(dpkg-query -W -f '${Status}' bumblebee 2>/dev/null) == install* ]]; then
        echo "Old Bumblebee package installation detected, removing..."
        if ! apt-get purge -y bumblebee; then
            echo "The old Bumblebee package could not be removed."
            echo "Installation aborted."
            exit 1
        fi
    fi

    [ -x /usr/local/bin/bumblebee-enablecard
    # Touched in postinst, but unused
    rm -vf /etc/default/bumblebee-initial

    # Bumblebee fails to clean up /etc/rc?.d, we'll do it if necessary
    update-rc.d -f bumblebee remove

    # Remove PPA if found to avoid conflicts
    if [ -f /etc/apt/sources.list.d/mj-casalogic-bumblebee-natty.list ]; then
        rm -vf /etc/apt/sources.list.d/mj-casalogic-bumblebee-natty.list
    fi
fi

if grep -iq opensuse /etc/issue; then
    :
fi

if grep -iq debian /etc/issue; then
    :
fi

# Distro-independent cleanup

# Do not show * if there is no matching file
shopt -s nullglob

# restore backed up files
for bashrc in \
    /etc/bashrc /etc/bash.bashrc \
    /etc/modprobe.d/blacklist.conf \
    /etc/modules \
    /etc/X11/xorg.conf \
    ; do
    [ -f "${file}.optiorig" ] && mv -v "${file}.optiorig" "$file"
done

for junk in \
    /etc/X11/xorg.conf.nvidia \
    /etc/init.d/bumblebee \
    /usr/local/bin/bumblebee-enablecard \
    /usr/local/bin/bumblebee-enablecard.old \
    /usr/local/bin/bumblebee-disablecard \
    /usr/local/bin/bumblebee-disablecard.old \
    /usr/local/bin/optirun \
    /usr/local/bin/optirun32 \
    /usr/local/bin/optirun64 \
    /usr/local/bin/bumblebee-disablecard-on-powerup \
    /usr/local/bin/bumblebee* \
    /etc/default/bumblebee \
    /etc/alternatives/xorg_extra_modules-bumblebee \
    /etc/bash_completion.d/optirun* \
    ; do
    [ -f "$junk" ] && rm -vf "$junk"
done

for junk_dirs in \
    /usr/share/doc/bumblebee \
    /usr/share/doc/packages/bumblebee \
    ; do
    [ -d "$junk" ] && rm -rvf "$junk"
done
