#!/bin/bash
OVERRIDEAUTODETECT=false
while [ $# -gt 0 ]; do
    case "$1" in
      --force)
        OVERRIDEAUTODETECT=true
        ;;
      --)
        shift
        break
        ;;
      *)
        echo "Unknown option: $1"
        exit 255
        ;;
    esac
    shift
done
if ! $OVERRIDEAUTODETECT; then
    if [ ! -f "/etc/bumblebee" ]; then
        echo "There is no ancient version to cleanup, to override this, run"
        echo "this program with the --force option."
        exit 1
    fi
fi

# Only apply changes on existing unmodded uninstallers
if [ -x /usr/local/bin/bumblebee-uninstall ] &&
    ! grep -q -e '--unattended' /usr/local/bin/bumblebee-uninstall; then
    # don't require sudo, replace lines about messing in home directories by
    # the no-op operator, make sure that the uninstaller returns 1 on failure
    # and stop slowing down by five seconds
    sed -i /usr/local/bin/bumblebee-uninstall \
        -e 's,\[ "\$HOME" == "/root" \],false,' \
        -e 's/^ .*\$HOME.*/:/;s,exit 0,exit 1,;/sleep 5/d'

    # allow for an unattended uninstallation
    CHECK='for arg; do [[ $arg == --unattended ]] && break; done && answer=Y || \\'
    sed -i /usr/local/bin/bumblebee-uninstall -e "/read answer/i $CHECK"

    # finally, reaching EOF is success
    echo 'exit 0' >> /usr/local/bin/bumblebee-uninstall
fi

# Distro-specific cleanups
if grep -iq ubuntu /etc/issue; then
    if [[ $(dpkg-query -W -f '${Status}' bumblebee 2>/dev/null) == install* ]]; then
        echo "Old Bumblebee package installation detected, removing..."
        if ! apt-get purge -y bumblebee; then
            echo "The old Bumblebee package could not be removed."
            echo "Installation aborted."
            exit 1
        fi
    fi
    # Touched in postinst, but unused
    rm -vf /etc/default/bumblebee-initial

    # Bumblebee fails to clean up /etc/rc?.d, we'll do it if necessary
    update-rc.d bumblebee remove

    # Remove PPA if found to avoid conflicts
    if [ -f /etc/apt/sources.list.d/mj-casalogic-bumblebee-natty.list ]; then
        rm -vf /etc/apt/sources.list.d/mj-casalogic-bumblebee-natty.list
    fi
fi


# Common cleanup
for junk in \
    /usr/local/bin/bumblebee-enablecard \
    /usr/local/bin/bumblebee-enablecard.old \
    /usr/local/bin/bumblebee-disablecard \
    /usr/local/bin/bumblebee-disablecard.old \
    ; do
    if [ -f "$junk" ]; then
        rm -vf "$junk"
    fi
done
