#!/bin/bash

. stages/checkprivileges

. stages/determinedistro
echo "${DISTRO}-based distribution found"

. stages/setvars

. stages/welcome

echo "== Installing dependencies =="
. "stages/$distro/packageinstall"

