#!/bin/bash
#
#
dependencies=('VirtualGL' 'nvidia-gfxG02')
missing_dependencies=()
failed=false
suse_version=$(cat /etc/SuSE-release | grep VERSION | cut -f3 -d" ")
kernel_type=$(uname -r | cut -f3 -d"-")


pkg_is_installed() {
    local pkg="$1"
    [[ -n $(rpm -qa $pkg*) ]]
}

for package in "${dependencies[@]}" ; do
    if ! pkg_is_installed "$package" ; then
        missing_dependencies[${#missing_dependencies[@]}]="$package"
    fi
done

if [ ${#missing_dependencies[@]} -gt 0 ] ; then
    #
    # Bumblebee is unlikely to be installed with missing these dependencies, so
    # we can skip checks whether we've installed the bumblebee package or not
    #
    echo "Missing dependencies: ${missing_dependencies[*]}"

    #
    #   Tell the user what to do when a depency is missing. 
    #
   for dependency in "${missing_dependencies[@]}" ; do
        if [[ "$dependency" == "VirtualGL" ]] ; then
            if [[ -n $(zypper lr "Bumblebee" 2>/dev/null | grep Cache) ]] ; then
                echo "'$dependency' can be installed from the Bumblebee repository which can be added by running:"
                echo "    sudo zypper ar -f http://download.opensuse.org/repositories/home:/Bumblebee-Project:/Bumblebee/openSUSE_$suse_version \"Bumblebee\""
                echo
            fi

            echo "Update your package lists and install the dependencies by running:"
            echo "    sudo zypper update"
            echo "    sudo zypper install $dependency"

            break
        fi

        if [[ "$dependency" == "nvidia-gfxG02" ]] ; then
            if [[ -n $(zypper lr "nVidia Graphics Drivers" 2>/dev/null | grep Cache) ]] ; then
                echo "nVidia drivers can be installed from the nVidia repository which can be added by running:"
                echo "    sudo zypper ar -f ftp://download.nvidia.com/opensuse/$suse_version \"nVidia Graphics Drivers\""
                echo
            fi

            echo "Update your package lists and install the dependencies by running:"
            echo "    sudo zypper update"
            echo "    sudo zypper install nvidia-gfxG02-kmp-$kernel_type"
            echo "    sudo zypper install x11-video-nvidiaG02"

            break
        fi
    done
    failed=true
fi

if pkg_is_installed bumblebee ; then
    echo "The 'bumblebee' package is already installed (from a repository?)."
    echo "The package needs to be removed before installing this version."
    echo "Please remove it by running:"
    echo "    sudo rpm -e bumblebee"
    failed=true
fi

$failed && exit 4
