#!/bin/bash
#
#
dependencies=('VirtualGL')
missing_dependencies=()
conflictingpackages=()
conflicts=()
failed=false
suse_version=$(cat /etc/SuSE-release | grep VERSION | cut -f3 -d" ")
kernel_type=$(uname -r | cut -f3 -d"-")


pkg_is_installed() {
    [[ -n $(rpm -qa $1*) ]]
}

#
# Get the right dependency for each driver
#
case "$DRIVER" in
  nvidia)
    dependencies[ ${#dependencies[@]} ]=nvidia-gfxG02-kmp
    conflictingpackages=()
    ;;
  nouveau)
    dependencies[ ${#dependencies[@]} ]=xorg-x11-driver-video-nouveau
    conflictingpackages=('nvidia-gfxG02-kmp')
    ;;
esac

#
# Check for conflicting packages
#
for package in "${conflictingpackages[@]}" ; do
    if pkg_is_installed "$package" ; then
        conflicts[${#conflicts[@]}]="$package"
    fi
done

if [ ${#conflicts[@]} -gt 0 ] ; then
    #
    # Bumblebee is unlikely to work with these conflicting packages
    #
    echo "Conflicting packages: ${conflicts[*]}"

    echo "These package need to be removed before installing this version."
    echo "Please remove them by running:"

    for conflict in "${conflicts[@]}" ; do
        if [[ "$conflict" == "nvidia-gfxG02-kmp" ]] ; then
            echo "    sudo rpm -e x11-video-nvidiaG02"
            echo "    sudo rpm -e nvidia-computeG02"
            echo "    sudo rpm -e nvidia-gfxG02-kmp-desktop"
        else
            echo "    sudo rpm -e $conflict"
        fi
    done

    exit 4
fi

#
# Check the dependencies
#
for package in "${dependencies[@]}" ; do
    if ! pkg_is_installed "$package" ; then
        missing_dependencies[${#missing_dependencies[@]}]="$package"
    fi
done

if [ ${#missing_dependencies[@]} -gt 0 ] ; then
    #
    # Bumblebee is unlikely to work with these missing dependencies
    #
    echo "Missing dependencies: ${missing_dependencies[*]}"
    echo

    #
    #   Tell the user about missing repos when needed
    #
   for dependency in "${missing_dependencies[@]}" ; do
        if [[ "$dependency" == "VirtualGL" ]] ; then
            if [[ "$(zypper --no-refresh info $dependency | grep Installed: | cut -f2 -d' ')" == "" ]] ; then
                if [[ ! -n $(zypper lr "Bumblebee Unstable" 2>/dev/null | grep Cache) ]] ; then
                    echo "'$dependency' can be installed from the Bumblebee Unstable repository which can be added by running:"
                    echo "    sudo zypper ar -f http://download.opensuse.org/repositories/home:/Bumblebee-Project:/Bumblebee-unstable/openSUSE_$suse_version \"Bumblebee Unstable\""
                    echo
                fi
            fi
        fi

        if [[ "$dependency" == "nvidia-gfxG02-kmp" ]] ; then
            if [[ "$(zypper --no-refresh info nvidia-gfxG02-kmp-$kernel_type  | grep Installed: | cut -f2 -d' ')" == "" ]] ; then
                if [[ ! -n $(zypper lr "nVidia Graphics Drivers" 2>/dev/null | grep Cache) ]] ; then
                    echo "nVidia drivers can be installed from the nVidia repository which can be added by running:"
                    echo "    sudo zypper ar -f ftp://download.nvidia.com/opensuse/$suse_version \"nVidia Graphics Drivers\""
                    echo
                fi
            fi
        fi
    done

    #
    #   Tell the user what to do when a depency is missing. 
    #
   echo "Update your package lists and install the dependencies by running:"
   echo "    sudo zypper refresh"

   for dependency in "${missing_dependencies[@]}" ; do
        if [[ "$dependency" == "VirtualGL" ]] ; then
            echo "    sudo zypper install $dependency"
        fi

        if [[ "$dependency" == "nvidia-gfxG02-kmp" ]] ; then
            echo "    sudo zypper install nvidia-gfxG02-kmp-$kernel_type"
            echo "    sudo zypper install x11-video-nvidiaG02"
        fi
    done
    failed=true
fi

if pkg_is_installed bumblebee ; then
    echo "The 'bumblebee' package is already installed (from a repository?)."
    echo "The package needs to be removed before installing this version."
    echo "Please remove it by running:"
    echo "    sudo rpm -e bumblebee"
    failed=true
fi

$failed && exit 4
