#!/bin/bash
install -m644 install-files/drivers/nvidia.options.opensuse "$LIBDIR/drivers"
install -m755 install-files/bumblebee.script.opensuse /etc/init.d/bumblebee
install -m644 install-files/optirun.bash_completion "/etc/bash_completion.d/optirun.sh"
