#!/bin/bash
PACMAN=$(which pacman)
dependencies=('virtualgl-bin')
conflictingpackages=('bumblebee' 'bumblebee-git' 'bumblebee-nouveau' 'bumblebee-nouveau-git' 'bumblebee-develop-git')
missing_dependencies=()
failed=false

conflictingpackages=('bumblebee' 'bumblebee-nouveau' 'bumblebee-nouveau-git' 'bumblebee-git' 'bumblebee-develop-git')
for i in "${conflictingpackages[@]}"; do
    if $PACMAN -Qq "$i" &>/dev/null ; then
        echo "Please uninstall conflicting package: $i"
        failed=true
    fi
done

for driver in "${DRIVERS[@]}"; do
    case "$driver" in
      nvidia)
        for i in dkms-nvidia nvidia-utils-bumblebee
        do
            dependencies[${#dependencies[@]}]="$i"
        done
        ;;
      nouveau)
        for i in nouveau-dri xf86-video-nouveau mesa libgl
        do
            dependencies[${#dependencies[@]}]="$i"
        done
        ;;
    esac
done

for package in "${dependencies[@]}"; do
    if ! "$PACMAN" -Qq "$package" &>/dev/null; then
        missing_dependencies[${#missing_dependencies[@]}]="$package"
    fi
done

if [ ${#missing_dependencies[@]} -gt 0 ]; then
    echo "Missing dependencies: ${missing_dependencies[*]}"
    echo "These packages are available from the AUR"
    failed=true
fi

$failed && exit 4
