#!/bin/bash
PACMAN=$(which pacman)
failed=false

conflictingpackages=('bumblebee' 'bumblebee-nouveau' 'bumblebee-nouveau-git' 'bumblebee-git' 'bumblebee-develop-git')
for i in "${conflictingpackages[@]}"; do
    if $PACMAN -Qq "$i" &>/dev/null ; then
        echo "Please uninstall conflicting package: $i"
        failed=true
    fi
done

dependencies=('virtualgl-bin' 'dkms-nvidia' 'nvidia-utils-bumblebee')
missing_dependencies=()
for package in "${dependencies[@]}"; do
    if ! "$PACMAN" -Qq "$package" &>/dev/null; then
        missing_dependencies[${#missing_dependencies}]="$package"
    fi
done
if [ ${#missing_dependencies} -gt 0 ]; then
    echo "Missing dependencies: ${missing_dependencies[*]}"
    echo "These packages are available from the AUR"
    failed=true
fi

$failed && exit 4
