#!/bin/bash
for i in bumblebee bumblebee-nouveau bumblebee-nouveau-git bumblebee-git
do
    if $PACMAN -Qq $i&>/dev/null ; then
        echo "Uninstalling conflicting package: $i"
        $PACMAN -R $i
    fi
done
