#!/bin/bash
# Copyright (C) 2011 Bumblebee Project
#
# This file is part of Bumblebee.
#
# Bumblebee is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bumblebee is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bumblebee.  If not, see <http://www.gnu.org/licenses/>.

# The line below should never be removed and should match regex: *# *BEE..
# BEE_UNINSTALLER_NEW DO NOT REMOVE THIS LINE

# Exit codes:
# 0 - uninstall was succesful
# 1 - uninstallation could not be started (confirmation rejected, insufficient
#     privileges)
# 2 - Uninstall failure - nothing was removed but services might be stopped
# 3 - Uninstall failure - unstable state (half-removed)

UNATTENDED=false
KEEP_CONFFILE=false
VERBOSE=false
CONFDIR=/etc/bumblebee

while [ $# -gt 0 ]; do
    case "$1" in
      --unattended)
        UNATTENDED=true
        ;;
      --upgrade)
        KEEP_CONFFILE=true
        ;;
      -v|--verbose)
        VERBOSE=true
        ;;
      --)
        shift
        break
        ;;
      --help)
        cat <<EOF
Usage: $0 [options]
  --unattended
    Do not confirm, proceed with uninstallation

  --upgrade
    Upgrade mode, do not remove configuration files

  --verbose
  -v
    Display files being removed

  --help
    Show this help message
EOF
        exit 0
        ;;
      *)
        # remember our policy on GH-14: ignore unrecognized options
        echo "Ignored unrecognized option: '$1'"
        ;;
    esac
    shift
done

if (( EUID != 0 )); then
    echo "You do not have sufficient privileges to uninstall Bumblebee"
    echo
    if which sudo &>/dev/null; then
        echo "Please run: sudo $0"
    else
        echo "Please run this script as root"
    fi
    echo
    exit 1
fi

if ! $UNATTENDED; then
    echo "You are about to uninstall Bumblebee."
    read -p "Continue ? (y / n) " yn
    if [[ $yn != [Yy]* ]]; then
        echo "Aborted."
        exit 1
    fi
fi

echo "Stopping services..."
# REPLACE WITH STOP SERVICE

echo "Removing services..."
# REPLACE WITH REMOVE SERVICE

uninstall() {
    local file="$1"
    if $KEEP_CONFFILE && [[ $file == "$CONFDIR/"* ]]; then
        $VERBOSE && echo "Not removing $file"
        return
    fi
    if $VERBOSE; then
        rm -vf "$1"
    else
        rm -f "$1"
    fi
}
uninstall_dir() {
    local dir="$1"
    if $KEEP_CONFFILE && [[ $dir/ == "$CONFDIR/"* ]]; then
        $VERBOSE && echo "Not removing $dir"
        return
    fi
    if $VERBOSE; then
        rmdir -v "$1"
    else
        rmdir "$1"
    fi
}

# Begin uninstallation of files
# REPLACE WITH UNINSTALL COMMANDS

# XXX: check if I am allowed to be removed
# remove myself. Note: do not source this file, or /bin/bash will be removed!
if $VERBOSE; then
    rm -vf "$0"
else
    rm -f "$0"
fi
echo "Bumblebee has been uninstalled."
