#!/bin/bash
# Copyright (C) 2011 Bumblebee Project
#
# This file is part of Bumblebee.
#
# Bumblebee is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Bumblebee is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Bumblebee.  If not, see <http://www.gnu.org/licenses/>.

if (( EUID != 0 )); then
    echo "Certain system information can only be gathered as root. This"
    echo "includes the machine manufacturer and model."
    echo
    if which sudo &>/dev/null; then
        echo "Please run: sudo ${0##*/}"
    else
        echo "Please run this script as root"
    fi
    echo
    exit 1
fi

# These tools need to be able to accept multiple packages as arguments
PKG_QUERY_TOOLS=(
    'apt-cache policy'
    'dpkg-query --show'
    'pacman -Q'
)
if grep -iqE 'Ubuntu|Linux Mint|Backtrack 5' /etc/issue; then
    DISTRO=ubuntu
elif grep -iq "Arch Linux" /etc/issue; then
    DISTRO=archlinux
elif grep -iq Fedora /etc/issue; then
    DISTRO=fedora
    echo "You are running Fedora, the work is in progress for you distro but not"
    echo "sufficient."
    echo "This tool may fail to generate a useful bugreport"
    #echo "please visit https://github.com/Bumblebee-Project/Bumblebee/issues"
    #exit 3
elif grep -iq OpenSUSE /etc/issue; then
    DISTRO=opensuse
    echo "You are running openSUSE, the work is in progress for you distro but not"
    echo "sufficient."
    echo "This tool may fail to generate a useful bugreport"
    #echo "please visit https://github.com/Bumblebee-Project/Bumblebee/issues"
    #exit 3
elif grep -iq Debian /etc/issue; then
    DISTRO=debian
    echo "You are running Debian Linux, please see the debumblebee project for support:"
    echo "https://github.com/z0rc/debumblebee"
    echo "This tool may fail to generate a useful bugreport"
elif grep -iq "Gentoo" /etc/issue; then
    DISTRO=gentoo
    echo "You are running Gentoo Linux, please see the ebuild here for support:"
    echo "https://github.com/iegor/rainyday/tree/master/x11-misc/bumblebee"
    echo "This tool may fail to generate a useful bugreport"
else
    echo "Your Distribution could not be determined or is not supported."
    echo "Please report a bug at:"
    echo "https://github.com/Bumblebee-Project/Bumblebee/issues"
    echo "This tool may fail to generate a useful bugreport"
fi

echo "${DISTRO}-based distribution detected"

PKG_QUERY_TOOL=
PACKAGES=
LIB_DIRS=

# Auto-detect packager tool
for tool in "${PKG_QUERY_TOOLS[@]}"; do
    if which "${tool%% *}" &>/dev/null; then
        PKG_QUERY_TOOL="$tool"
        break
    fi
done

# XXX: perhaps LIB_DIRS can be separated from the tools
case "$PKG_QUERY_TOOL" in
  apt-cache*|dpkg-query*)
    PACKAGES=(bumblebee virtualgl nvidia-current nvidia-glx)
    LIB_DIRS=(
        /usr/lib/nvidia-current /usr/lib32/nvidia-current /usr/lib/nvidia
        /usr/lib/nvidia/i386-linux-gnu /usr/lib/nvidia/x86_64-linux-gnu
    )
    ;;
  pacman*)
    PACKAGES=(bumblebee lib32-nvidia-utils-bumblebee nvidia-utils-bumblebee virtualgl-bin virtualgl32-bin)
    LIB_DIRS=(/usr/lib/nvidia-bumblebee /usr/lib32/nvidia-bumblebee)
    ;;
  *)
    # unknown package management tool :/
    ;;
esac

echo
echo "Bug report is being generated"
echo

# Can you read Japanese? I don't.
export LANG=C LC_MESSAGES=C

BUGREPORT_DIR="$(mktemp -d)"
BUGREPORT_FILE="$BUGREPORT_DIR"/bumblebee-report
BUGREPORT_NAME="bumblebee-bugreport-$(date +%Y%m%d_%H%M%S)"

cp /var/log/Xorg.* "$BUGREPORT_DIR"
cp -r /etc/bumblebee "$BUGREPORT_DIR"
cp /var/log/bumblebee.* "$BUGREPORT_DIR"

header() {
    printf '\n=== %s ===\n' "$1"
}

{ # Start bug report
header "Bumblebee Bug Report"
echo "$BUGREPORT_NAME"
date -R -u

header "dmidecode"

for key in baseboard-manufacturer baseboard-product-name baseboard-version \
    system-manufacturer system-product-name system-version; do
    printf "%22s : %s\n" "$key" "$(dmidecode --string "$key")"
done

header "System Information"
uname -a
echo "/etc/issue:"
cat /etc/issue
if which lsb_release &>/dev/null; then
    echo "lsb_release -a:"
    lsb_release -a
fi

header "lspci overview"
lspci -nn

header "lspci on nvidia devices"
lspci -d 10de: -vvnn

header "Process information info"
PIDS=$(pidof $(which X Xorg bumblebee optirun optirun32 optirun64 2>/dev/null))
[ -n "$PIDS" ] && ps uww --pid "$PIDS"

header "Library paths"

for lib in "${LIB_DIRS[@]}"
do
    if [ -d "$lib" ]; then
        echo "$lib:"
        ls --group-directories-first -laR "$lib"
    fi
done

header "Modules info"
lsmod

header "Alternatives info"
ls -lat /etc/alternatives


header "Packages info"
echo "Using tool: $PKG_QUERY_TOOL"
$PKG_QUERY_TOOL "${PACKAGES[@]}"

# End bug report
} &>> "$BUGREPORT_FILE"

tar zcf "${BUGREPORT_NAME}.tar.gz" -C "$BUGREPORT_DIR" .

echo "Bug report generated"
echo
echo "The bug report has been saved as '${BUGREPORT_NAME}.tar.gz'"
echo "Please create an issue on Github and email the bugreport file including"
echo "the issue number to bumblebee@lists.launchpad.net"
echo
echo "https://github.com/Bumblebee-Project/Bumblebee/issues"
echo
echo "This really makes bugfixing much easier for us and faster for you"
echo
echo "Thanks for your help!"
echo "The Bumblebee Project Team"
