#!/bin/bash

#
# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# <mj@casalogic.dk> wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return Martin Juhl
# ----------------------------------------------------------------------------
#

#    This file is part of bumblebee.
#
#    bumblebee is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    bumblebee is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with bumblebee.  If not, see <http://www.gnu.org/licenses/>.
#


ROOT_UID=0

if grep -iqE 'Ubuntu|Linux Mint|Backtrack 5' /etc/issue; then
    DISTRO=UBUNTU
elif grep -iq "Arch Linux" /etc/issue; then
    DISTRO=ARCHLINUX
fi

if (( EUID != 0 )); then
    echo "You do not have sufficient privileges to install Bumblebee"
    echo
    if which sudo; then
        echo "Please run: sudo ./install"
    else
        echo "Please run this script as root"
    fi
    echo
    exit 1
fi

echo
echo "Bug report is being generated"
echo

rm -rf /tmp/bug-report
mkdir -p /tmp/bug-report

cp /var/log/Xorg.* /tmp/bug-report/
cp /etc/bumblebee/xorg.conf* /tmp/bug-report/
cp /var/log/bumblebee.* /tmp/bug-report/
cp /etc/bash.bashrc /tmp/bug-report/


echo "Bumblebee Bug Report" >> /tmp/bug-report/bumblebee-report
echo >> /tmp/bug-report/bumblebee-report

echo `cat /etc/bumblebee/bumblebee.conf` >> /tmp/bug-report/bumblebee-report
echo >> /tmp/bug-report/bumblebee-report

echo `cat /etc/issue` >> /tmp/bug-report/bumblebee-report
echo >> /tmp/bug-report/bumblebee-report

echo "uname -a info" >> /tmp/bug-report/bumblebee-report
echo >> /tmp/bug-report/bumblebee-report
uname -a >> /tmp/bug-report/bumblebee-report
echo >> /tmp/bug-report/bumblebee-report

echo "lspci info" >> /tmp/bug-report/bumblebee-report
echo >> /tmp/bug-report/bumblebee-report
lspci >> /tmp/bug-report/bumblebee-report
echo >> /tmp/bug-report/bumblebee-report

echo "ps aux info" >> /tmp/bug-report/bumblebee-report
echo >> /tmp/bug-report/bumblebee-report
ps aux | grep X >> /tmp/bug-report/bumblebee-report
echo >> /tmp/bug-report/bumblebee-report

echo "library info" >> /tmp/bug-report/bumblebee-report
echo >> /tmp/bug-report/bumblebee-report

if [ -d /usr/lib32/nvidia-current ]; then
    echo "/usr/lib32/nvidia-current/" >> /tmp/bug-report/bumblebee-report
    echo >> /tmp/bug-report/bumblebee-report
    ls -la /usr/lib32/nvidia-current >> /tmp/bug-report/bumblebee-report
    echo >> /tmp/bug-report/bumblebee-report
fi

if [ -d /usr/lib64/nvidia-current ]; then
    echo "/usr/lib64/nvidia-current/" >> /tmp/bug-report/bumblebee-report
    echo >> /tmp/bug-report/bumblebee-report
    ls -la /usr/lib64/nvidia-current >> /tmp/bug-report/bumblebee-report
    echo >> /tmp/bug-report/bumblebee-report
fi

if [ -d /usr/lib/nvidia-current ]; then
    echo "/usr/lib/nvidia-current/" >> /tmp/bug-report/bumblebee-report
    echo >> /tmp/bug-report/bumblebee-report
    ls -la /usr/lib/nvidia-current >> /tmp/bug-report/bumblebee-report
    echo >> /tmp/bug-report/bumblebee-report
fi

echo "modules info" >> /tmp/bug-report/bumblebee-report
echo >> /tmp/bug-report/bumblebee-report
lsmod >> /tmp/bug-report/bumblebee-report 
echo >> /tmp/bug-report/bumblebee-report

echo "alternatives info" >> /tmp/bug-report/bumblebee-report
echo >> /tmp/bug-report/bumblebee-report
ls -la /etc/alternatives >> /tmp/bug-report/bumblebee-report
echo >> /tmp/bug-report/bumblebee-report

echo "dmidecode" >> /tmp/bug-report/bumblebee-report
echo >> /tmp/bug-report/bumblebee-report
dmidecode --string baseboard-manufacturer >> /tmp/bug-report/bumblebee-report
dmidecode --string baseboard-product-name >> /tmp/bug-report/bumblebee-report
dmidecode --string baseboard-version >> /tmp/bug-report/bumblebee-report
dmidecode --string system-manufacturer >> /tmp/bug-report/bumblebee-report
dmidecode --string system-product-name >> /tmp/bug-report/bumblebee-report
dmidecode --string system-version >> /tmp/bug-report/bumblebee-report

tar zcf $HOME/bumblebee-bugreport-`date +2%3y%m%d_%H%M%S`.tar.gz /tmp/bug-report/

echo "Bug report generated"
echo
echo "The bug report has been saved as "$HOME/bumblebee-bugreport-`date +2%3y%m%d_%H%M%S`.tar.gz
echo "Please create a bugreport on github and email me the bug report along with the"
echo "issue number to bumblebee@lists.launchpad.net"
echo
echo "https://github.com/Bumblebee-Project/Bumblebee/issues"
echo 
echo "This really makes bugfixing much easier for us and faster for you"
echo
echo "Martin Juhl / MrMEEE & The Bumblebee Project Team"
