#!/bin/bash

#
# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# <mj@casalogic.dk> wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return Martin Juhl
# ----------------------------------------------------------------------------
#

#    This file is part of bumblebee.
#
#    bumblebee is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    bumblebee is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with bumblebee.  If not, see <http://www.gnu.org/licenses/>.
#


ROOT_UID=0

if grep -iqE 'Ubuntu|Linux Mint|Backtrack 5' /etc/issue; then
    DISTRO=UBUNTU
elif grep -iq "Arch Linux" /etc/issue; then
    DISTRO=ARCHLINUX
fi

if (( EUID != 0 )); then
    echo "You do not have sufficient privileges to install Bumblebee"
    echo
    if which sudo &>/dev/null; then
        echo "Please run: sudo ./install"
    else
        echo "Please run this script as root"
    fi
    echo
    exit 1
fi

# Determine Arch x86_64 or i686
ARCH=`uname -m`

# Get tools location
LSPCI="$(which lspci)"
MODPROBE="$(which modprobe)"

# Get terminal size
LINES=`stty size | cut -f1 -d' '`
COLUMNS=`stty size | cut -f2 -d' '`

CONFDIR=/etc/bumblebee
NVIDIA_LIBDIR=/usr/lib/nvidia-current

echo
echo "Configuring... Please wait"
echo

NVIDIABUSID=$("$LSPCI" -d 10de: -n | grep '030[02]:' | cut -d' ' -f1 | tr . :)

if [ -z "$NVIDIABUSID" ]; then
    whiptail --msgbox \
" The BusID of the nVidia card can't be determined.\n"\
"You must correct this manually in /etc/bumblebee/xorg.conf.nvidia\n"\
"Please report this problem..\n\n"\
"Press enter to continue." $LINES $COLUMNS
fi

re_busid='^( *BusID +")[^"]*'

for driver in nvidia; do
    echo "Setting Bus ID in xorg.conf.$driver..."
    sed -E -i "$CONFDIR/xorg.conf.$driver" \
        -e "s,${re_busid},\1${NVIDIABUSID},"
done

CONNECTEDMONITOR="UNKNOWN"

if [ "$DISTRO" == "UBUNTU" ] ; then

    ${MODPROBE} nvidia-current
    query_info=$(LD_LIBRARY_PATH="$NVIDIA_LIBDIR" "$NVIDIA_LIBDIR"/bin/nvidia-xconfig --query-gpu-info)
    if [ $(grep "Display Devices" <<<"$query_info" | cut -d: -f2) -gt 0 ]; then
        CONNECTEDMONITOR=$(grep "Display Device 0" <<< "$query_info " | cut -d\( -f2 | cut -d\) -f1)
    fi
    ${MODPROBE} -r nvidia
fi

if [ "$CONNECTEDMONITOR" != "CRT-0" ] && [ "$CONNECTEDMONITOR" != "DFP-0" ];then
    LIST_SIZE=$(($LINES - 10))
choice=$(whiptail --nocancel --menu \
" The device for the nVidia monitor could not be detected, please\n"\
"manually choose the device, if your having problems, try another." $LINES $COLUMNS $LIST_SIZE 1 "CRT-0" 2 "DFP-0" 3 "Manually Enter" 3>&1 1>&2 2>&3)
    case "$choice" in
      1)
        CONNECTEDMONITOR="CRT-0"
        ;;
      2)
        CONNECTEDMONITOR="DFP-0"
        ;;
      3)
        CONNECTEDMONITOR=$(whiptail --inputbox " Enter the nVidia connected monitor:" $LINES $COLUMNS 3>&1 1>&2 2>&3)
        ;;
    esac
fi

sed -i "s/\([ \t]*Option[ \t]*\"ConnectedMonitor\"[ \t]*\)".*"/\1\"$CONNECTEDMONITOR\"/g" $CONFDIR/xorg.conf.nvidia



if [ "$DISTRO" == "UBUNTU" ] ; then
    update-rc.d bumblebee defaults
fi


LIST_SIZE=$(($LINES - 10))
choice=$(whiptail --nocancel --menu --default-item 3 \
" The Image Transport is how the images are transferred from the\n"\
"nVidia card to the Intel card, people has different experiences of\n"\
"performance, but just select the default if you are in doubt.\n\n"\
"I recently discovered that yuv and jpeg both has some lagging\n"\
"this is only noticable in fast moving games, such as 1st person\n"\
"shooters and for me, its only good enough with xv, even though\n"\
"xv brings down performance a little." $LINES $COLUMNS $LIST_SIZE 1 "YUV" 2 "JPEG" 3 "PROXY (Default)" 4 "XV" 5 "RGB" 3>&1 1>&2 2>&3)

case "$choice" in
  1)
    IMAGETRANSPORT="yuv"
    ;;
  2)
    IMAGETRANSPORT="jpeg"
    ;;
  3)
    IMAGETRANSPORT="proxy"
    ;;
  4)
    IMAGETRANSPORT="xv"
    ;;
  5)
    IMAGETRANSPORT="rgb"
    ;;
  *)
    IMAGETRANSPORT="proxy"
    ;;
esac

sed -i 's/VGL_COMPRESS.*/VGL_COMPRESS='$IMAGETRANSPORT'/' "$CONFDIR/bumblebee.conf"

#
#    Set userrights
#
if ! grep -q '^bumblebee:' /etc/group; then
    groupadd bumblebee
fi

if [ "$DISTRO" == "UBUNTU" ] && [ -n "$SUDO_USER" ]; then
    gpasswd -a "$SUDO_USER" bumblebee
fi

#
#    That's all folks
#
whiptail --msgbox \
" Bumblebee is now configured.\n\n"\
"If you have any problems, please run bumblebee-bugreport\n\n"\
"Have fun...." $LINES $COLUMNS
