#!/bin/bash

# Some common configuration files
BUMBLEBEE_CONFDIR=/etc/bumblebee

# Full paths to possible optirun binaries
OPTIRUNS=()
OPTIRUNS[0]=$(which optirun)
# provided for backwards compatibility, optirun32 is deprecated in favor of
# optirun32 -32, optirun64 is equal to optirun
OPTIRUNS[1]=$(which optirun32)
OPTIRUNS[2]=$(which optirun64)

# daemon pidfile
BUMBLEBEE_PIDFILE=/var/run/bumblebee.pid
# communication file for the daemon
BUMBLEBEE_FIFO=/var/run/bumblebee.fifo


# The Xorg server binary
X_DAEMON=$(which X)

# The library path in which the X server can find libraries like GL
X_LD_LIBRARY_PATH=
# allow to set X_LD_LIBRARY_PATH if needed
if [ -s "${BUMBLEBEE_LIBDIR}/drivers/${DRIVER}.options" ]; then
    . "${BUMBLEBEE_LIBDIR}/drivers/${DRIVER}.options"
fi
