#!/bin/bash

# setup search paths
SEARCH_PATHS="/sbin /usr/sbin /bin /usr/bin"
# find lspci
for path in $SEARCH_PATHS ; do 
    [ -f $path/lspci ] && LSPCI=$path/lspci && break;
done
# find modprobe
for path in $SEARCH_PATHS ; do 
    [ -f $path/modprobe ] && MODPROBE=$path/modprobe && break;
done
# find rmmod
for path in $SEARCH_PATHS ; do 
    [ -f $path/rmmod ] && RMMOD=$path/rmmod && break;
done
# find modinfo
for path in $SEARCH_PATHS ; do 
    [ -f $path/modinfo ] && MODINFO=$path/modinfo && break;
done
# find usermod
for path in $SEARCH_PATHS ; do 
    [ -f $path/usermod ] && USERMOD=$path/usermod && break;
done
# if no path is found, try to use the default path
[[ ! -n "$LSPCI" ]] && LSPCI=lspci
[[ ! -n "$MODPROBE" ]] && MODPROBE=modprobe
[[ ! -n "$RMMOD" ]] && RMMOD=rmmod
[[ ! -n "$MODINFO" ]] && MODINFO=modinfo
[[ ! -n "$USERMOD" ]] && USERMOD=usermod

# Some common configuration files
BUMBLEBEE_CONFDIR=/etc/bumblebee

# usermod options
USERMOD_OPTS="-a -G $BUMBLEBEE_GROUP"

# Full paths to possible optirun binaries
OPTIRUNS=()
OPTIRUNS[0]=$(which optirun)
# provided for backwards compatibility, optirun32 is deprecated in favor of
# optirun -32, optirun64 is equal to optirun
OPTIRUNS[1]=$(which optirun32 2>/dev/null)
OPTIRUNS[2]=$(which optirun64 2>/dev/null)

# daemon pidfile
BUMBLEBEE_PIDFILE=/var/run/bumblebee.pid
# communication file for the daemon
BUMBLEBEE_FIFO=/var/run/bumblebee.fifo


# The Xorg server binary
X_DAEMON=$(which X)
