#!/bin/bash

# setup search paths
SEARCH_PATHS="/sbin /usr/sbin /bin /usr/bin"
# find lspci
for path in $SEARCH_PATHS ; do 
    [ -f $path/lspci ] && LSPCI=$path/lspci && break;
done
# if no path is found, try to use the default path
[[ ! -n "$LSPCI" ]] && LSPCI=lspci

# Some common configuration files
BUMBLEBEE_CONFDIR=/etc/bumblebee

# usermod options (options for Ubuntu / Arch Linux as default)
SUDO_OPTS=

# usermod options (options for Ubuntu / Arch Linux as default)
USERMOD_OPTS="-a -G $BUMBLEBEE_GROUP"

# Full paths to possible optirun binaries
OPTIRUNS=()
OPTIRUNS[0]=$(which optirun)
# provided for backwards compatibility, optirun32 is deprecated in favor of
# optirun -32, optirun64 is equal to optirun
OPTIRUNS[1]=$(which optirun32 2>/dev/null)
OPTIRUNS[2]=$(which optirun64 2>/dev/null)

# daemon pidfile
BUMBLEBEE_PIDFILE=/var/run/bumblebee.pid
# communication file for the daemon
BUMBLEBEE_FIFO=/var/run/bumblebee.fifo


# The Xorg server binary
X_DAEMON=$(which X)
