#!/bin/bash
dependencies=('virtualgl' 'nvidia-current')
missing_dependencies=()

pkg_is_installed() {
    local pkg="$1"
    [[ $(dpkg-query -W -f '${Status}' "$pkg" 2>/dev/null) =~ ^install ]]
}

for package in "${dependencies[@]}"; do
    if ! pkg_is_installed "$package"; then
        missing_dependencies[${#missing_dependencies}]="$package"
    fi
done

failed=false
# detect if cleanup is needed
if [ -f /etc/bumblebee ]; then
    echo "The installer detected an ancient installation of Bumblebee, possibly"
    echo "from the PPA mj-casalogic/bumblebee or git MrMEEE/bumblebee. Since"
    echo "that version has a lot of flaws, you will need to run the cleanup"
    echo "script first which can be done by running:"
    echo "    sudo ./cleanup"
    failed=true
fi

if [ ${#missing_dependencies} -gt 0 ]; then
    # bumblebee is unlikely to be installed with missing these dependencies, so
    # we can skip checks whether we've installed the bumblebee package or not
    echo "Missing dependencies: ${missing_dependencies[*]}"
    echo "VirtualGL can be installed from the Bumblebee PPA which can be added by running:"
    echo "    sudo add-apt-repository ppa:bumblebee/stable"
    echo "Update your package lists and install the dependencies by running:"
    echo "    sudo apt-get update"
    echo "    sudo apt-get install ${missing_dependencies[*]}"
    failed=true
fi

if pkg_is_installed bumblebee; then
    echo "The 'bumblebee' package is already installed (from a PPA?). Before"
    echo "this version can be installed, that package must be removed. That"
    echo "can be done by running:"
    echo "    sudo apt-get remove bumblebee"
    failed=true
fi

$failed && exit 4
