#!/bin/bash
if $PKGINSTALLED; then
    echo "Old Bumblebee package installation detected, removing..."
    if ! apt-get purge ${APT_OPTS} bumblebee; then
        echo "The old Bumblebee package could not be removed."
        echo "Installation aborted."
        exit 1
    fi
fi

if $ANCIENTINSTALLATIONFOUND; then
    # Touched in postinst, but unused
    rm -vf /etc/default/bumblebee-initial

    # Bumblebee fails to clean up /etc/rc?.d, we'll do it if necessary
    update-rc.d bumblebee remove

    # XXX: use awk magic on apt-cache policy to check whether the
    #      nvidia-current driver needs to be downgraded
    # XXX: maybe we should mark packages as auto so those can be removed
    #      if not used? (virtualgl, nvidia-current)

    # Remove PPA if found to avoid conflicts
    if [ -f /etc/apt/sources.list.d/mj-casalogic-bumblebee-natty.list ]; then
        rm -vf /etc/apt/sources.list.d/mj-casalogic-bumblebee-natty.list
    fi
fi
