#!/bin/bash
XORG_MODULEPATH=/usr/lib/nvidia-current/xorg,$XORG_MODULEPATH
CMD_SVC_REMOVE='update-rc.d -f bumblebee remove'
DRIVER_TO_MODPROBE=nvidia-current
X_LD_LIBRARY_PATH=$X_LD_LIBRARY_PATH-current
