#!/bin/bash
# Unified dependency checker. Each distro will need to define variables in the
# $DISTRO/setvars stage:
# PACKER_QUERY  - command line to query for packages
# CONF_PACKS    - array of conflicting packages
# DEP_PACKS     - array with dependencies packs

failed=false

# Check for conflicting packages. If they are present, print a message and exit 
# with failure state 4
for i in "${CONF_PACKS[@]}"; do
    if "$PACKER_QUERY" "$i" &>/dev/null ; then
        echo "Please uninstall conflicting package: $i"
        failed=true
    fi
done

# Check for missing dependencies. If they are not present, print a message and 
# exit with failure state 4
missing_dependencies=()
for package in "${DEP_PACKS[@]}"; do
    if ! "$PACKER_QUERY" "$package" &>/dev/null; then
        missing_dependencies[${#missing_dependencies[@]}]="$package"
    fi
done
if [ ${#missing_dependencies[@]} -gt 0 ]; then
    echo "Missing dependencies: ${missing_dependencies[*]}"
    failed=true
fi

$failed && exit 4
