#!/bin/bash
if (( EUID != 0 )); then
    echo "You do not have sufficient privileges to install Bumblebee"
    echo
    if which sudo &>/dev/null; then
        echo "Please run: sudo $0"
    else
        echo "Please run this script as root"
    fi
    echo
    exit 1
fi
