#!/bin/bash
# Unified dependency checker. Each distro will need to define variables in the
# $DISTRO/setvars stage:
# PACKER_QUERY  - command line to query for packages
# CONF_PACKS    - array of conflicting packages
# DEP_PACKS     - array with dependencies packs

failed=false

# Check for conflicting packages. If they are present, print a message and exit
# with failure state 4
conflicting_packages=()
for package in "${CONF_PACKS[@]}"; do
    if "$PACKER_QUERY" "$package" &>/dev/null ; then
        conflicting_packages[${#conflicting_packages[@]}]="$package"
    fi
done
if [ ${#conflicting_packages[@]} -gt 0 ]; then
    echo "Conflicting packages: ${conflicting_packages[*]}"
    failed=true
fi

# Check for missing dependencies. If they are not present, print a message and
# exit with failure state 4
missing_dependencies=()
for package in "${DEP_PACKS[@]}"; do
    if ! "$PACKER_QUERY" "$package" &>/dev/null; then
        missing_dependencies[${#missing_dependencies[@]}]="$package"
    fi
done
if [ ${#missing_dependencies[@]} -gt 0 ]; then
    echo "Missing dependencies: ${missing_dependencies[*]}"
    failed=true
fi

$failed && exit 4
