#!/bin/bash

if $ANCIENTINSTALLATIONFOUND; then
    echo "An ancient version of Bumblebee has been detected, cleaning up..."
    for junk in \
        /usr/local/bin/bumblebee-enablecard \
        /usr/local/bin/bumblebee-enablecard.old \
        /usr/local/bin/bumblebee-disablecard \
        /usr/local/bin/bumblebee-disablecard.old \
        ; do
        echo [ -f "$junk" ]; then
            rm -vf "$junk"
        fi
    done
fi
