#!/bin/bash

# Detect PCI Bus ID of the nVidia card
# -d 10de: shows devices from nvidia only
# 03 is the Display controller class
# 0300 is a VGA compatible controller
# 0302 is a 3D controller
# (information from /usr/share/misc/pci.ids and the manpage of lspci)
NVIDIABUSID=$("$LSPCI" -d 10de: -n | grep '030[02]:' | cut -d' ' -f1 | tr . :)

case $(wc -l <<<"$NVIDIABUSID") in
  0)
    echo "The BusID of the nVidia card can't be determined."
    ;;
  1)
    echo "Detected Bus ID: $NVIDIABUSID"
    ;;
  *)
    # You'll never know.
    echo "Multiple graphics cards are not supported by Bumblebee yet. The"
    echo "following PCI Bus IDs have been detected:"
    echo "$NVIDIABUSID"
    echo "If this information is wrong, please report it to:"
    echo "https://github.com/Bumblebee-Project/Bumblebee/issues"
    # empty the ID so we can detect this as error
    NVIDIABUSID=
    ;;
esac

if [ -z "$NVIDIABUSID" ]; then
    echo "Aborting installation"
    exit 1
fi

# Detect Monitor
# Don't work for OpenSUSE
# Ximi1970 to fix it ?

if [ ${DISTRO} = "ubuntu" ]; then
    NVIDIAMOD=-current
elif [ ${DISTRO} = "fedora" ]; then
    NVIDIAMOD=
fi

${MODPROBE} nvidia${NVIDIAMOD}

# Why only checking that for Fedora ?
if [ ${DISTRO} = "fedora" ] && [ ${ARCH} = "x86_64" ]; then
    NVIDIAARCH=64
else
    NVIDIAARCH=
fi

query_info=$(LD_LIBRARY_PATH=/usr/lib${NVIDIAARCH}/nvidia-current /usr/lib${NVIDIAARCH}/nvidia-current/bin/nvidia-xconfig --query-gpu-info)

if [ $(grep "Display Devices" <<<"$query_info" | cut -d: -f2) -gt 0 ]; then
    CONNECTEDMONITOR=$(grep "Display Device 0" <<< "$query_info " | cut -d\( -f2 | cut -d\) -f1)
fi

${MODPROBE} -r nvidia
