#!/bin/bash

# Determine whether it is a 32-bit (i686) or 64-bit (x86_64) machine
ARCH=$(uname -m)
UNATTENDED=false

for arg; do
    case "$arg" in
      --unattended)
        UNATTENDED=true
        ;;
      --help)
        echo "Usage: $0 [options]"
        echo
        echo "  --unattended"
        echo "    Do not pause with informational messages, proceed with the installation"
        echo "    without confirming"
        ;;
      *)
        echo "Unrecognized option '$arg'"
        echo "Try '$0 --help' for more information."
        ;;
    esac
done
