#!/bin/bash

uninstall_opts=('--upgrade')
$UNATTENDED && uninstall_opts[${#uninstall_opts[@]}]='--unattended'

uninstaller="$BINDIR/bumblebee-uninstall"
if [ -x "$uninstaller" ]; then
    echo "To install the new version, the old installation must be removed."
    echo "Running $uninstaller..."
    if ! "$uninstaller" "${uninstall_opts[@]}"; then
        echo "Uninstallation of old version failed, installation aborted."
        exit 5
    fi
    break
fi
