#!/bin/bash
if ! $UNATTENDED; then
	echo "Welcome to the installation of Bumblebee version $(cat VERSION)"
	echo "Licensed under Red Bull, BEER-WARE License and GPL"
	echo
	echo "This will enable you to utilize both your Intel and nVidia card"
	echo
	echo "Please note that this script will probably only work with Ubuntu, Debian,"
	echo "OpenSuSE and Fedora based machines"
	echo
	echo "Are you sure you want to proceed ? (y/n)"
	read answer
	if [[ $answer != [yY]* ]]; then
		echo "Installation aborted"
	fi
fi
